### ISSUE TITLE
Updated German translation for Interface.apk

### ISSUE THREAD

**Issue by Minty123** [Kryten2k35/JFLTE-GPE#1]
Hello there!

Your ROM is great! Though the interface settings aren't that well translated into German. Since you did not provide sources here, I decompiled the interface.apk and translated it more or less from scratch.

You can find the XML here: https://www.dropbox.com/s/3c0kayu377yqoy1/strings.xml?dl=0
It belongs to the folder res\values-de

Maybe you could also show me where I can find the strings for "Interface" and "Performance" in the system settings and the reboot options? These are also not translated yet

Have a great day!

**Comment by Kryten2k35** [comment]
Hi, 

The OTA Updates app source is here: https://github.com/Kryten2k35/OTAUpdates

:)
