### ISSUE TITLE
Phone becomes unresponsive when in a call

### ISSUE THREAD

**Issue by Mu5tank05** [Kryten2k35/JFLTE-GPE#10]
On my jfltexx when ringing someone the screen will go black and then none of the buttons seem to work, I have updated the ROM and factory reset everything with no solution.
This happens with any dialler app I have tried
Thanks

**Comment by k3nn3t** [comment]
Hey. Did you find a solution to this? 
I haw the same problem.

**Comment by Mu5tank05** [comment]
I found that the proximity sensor had become blocked by some dust, I simply used a can of compressed air around the front and back of phone (cover off)

**Comment by k3nn3t** [comment]
Tanx.
Did pull of my sensor and it was full of dust. Cleaned and working perfect now.
