### ISSUE TITLE
Navigation bar visible though height is set to zero in landscape

### ISSUE THREAD

**Issue by CharlyDelta** [Kryten2k35/JFLTE-GPE#11]
Release: JFLTE-GPE-20150210
I have changed the hardware context menu button to be the application menu, and followed the suggestion to show the software navigation bar with height=0 so the software context menu button will be displayed. This works fine, except when using the landscape mode in any app I have tried (for example Google Chrome or Play Newsstand)

**Comment by Kryten2k35** [comment]
I can fix this, but I think Dan wants to release tonight, and I haven't yet looked at it (been prepping for a Maths exam tomorrow, Wednesday).

**Comment by CharlyDelta** [comment]
I'm not in a hurry or anything, I just thought that using the github issue tracker is a good way to have an overview, since the xda posts are not really made for this ;) (I also have not seen any "known issues" section or anything yet)
Do whatever is best for you, since you are doing an awesome job

**Comment by danvdh** [comment]
we will post pone the update until Kryten fixes this issue,  its the only ongoing issue that needs to be fixed to my knowledge,  once he commits a fix we will update the changelog / build dates and release.  no new features are to be added until this release goes live.

gl on your exam Matt

**Comment by CharlyDelta** [comment]
Sounds like a plan :)  Thanks for your quick feedback

**Comment by Kryten2k35** [comment]
This is now fixed :)
