### ISSUE TITLE
After dirty flash, interface settings are unreachable

### ISSUE THREAD

**Issue by winek** [Kryten2k35/JFLTE-GPE#13]
Hello, and thank you for such a brilliant firmware for my phone!

The only major problem I've encountered is that after dirty flashing an update using TWRP, interface settings (Settings → Interface) are unreachable. Every time I try to launch them, the settings app crashes.

Here is what `adb logcat | grep -i settings` says just after an attempt:

    I/ActivityManager( 1113): START u0 {act=android.intent.action.MAIN cmp=com.ultima.settings/.SettingsActivity (has extras)} from uid 1000 on display 0
    E/AndroidRuntime( 9075): android.content.ActivityNotFoundException: Unable to find explicit activity class {com.ultima.settings/com.ultima.settings.SettingsActivity}; have you declared this activity in your AndroidManifest.xml?

After a clean reflash everything works. The interface settings are important to me, because I'd like to use a *menu to recents* configuration.

Is there a solution besides clean flashing?

**Comment by Kryten2k35** [comment]
Simply clear the settings of the interface app :)

**Comment by winek** [comment]
Thank you, will give a try after the next update.

**Comment by lifebearups** [comment]
Sorry if the question is stupid. I am having the same problem with the interface option, I came here looking to fix it, but I can't figure out how to cleat the setting of interface app. How can I do it?

By the way, thank you for your awesome work!
