### ISSUE TITLE
aroma-config

### ISSUE THREAD

**Issue by 0o0TheDude0o0** [Kryten2k35/JFLTE-GPE#6]
I could be wrong but...

Line 217 of META-INF/com/google/android/aroma-config

if file_getprop("/tmp/aroma-data/wipe.prop","kernel") == "googymax" then

Should read

if file_getprop("/tmp/aroma-data/install.prop","kernel") == "googymax" then

**Comment by Kryten2k35** [comment]
Nice catch! :+1: 

Kryten2k35/JFLTE-GPE@7d313f86959422c0bde2eb428b69bbe121e91af3
