### ISSUE TITLE
Interface/Battery Status Style - percent inside the icon issue

### ISSUE THREAD

**Issue by 0o0TheDude0o0** [Kryten2k35/JFLTE-GPE#7]
When switching battery icon styles and selecting percent inside the icon, percent stays outside the icon. Persistent after reboots...
![screenshot_2015-02-01-16-26-21](https://cloud.githubusercontent.com/assets/6024672/5994191/6ad326b8-aa2f-11e4-87a5-4427b32a8dd1.png)

**Comment by Kryten2k35** [comment]
Only while charging ;)

**Comment by 0o0TheDude0o0** [comment]
Sure enough... Disregard!

**Comment by Kryten2k35** [comment]
I thought so too when I was porting the stuff over. I got all annoyed because I thought something had gone wrong! Then I realised :+1: 

Keep the testing coming!

**Comment by 0o0TheDude0o0** [comment]
Annoyed me too because I knew that at one point the percent was inside and I did not put it together either ;)
